version: "3"
services:
  poste:
    image: analogic/poste.io
    container_name: poste
    hostname: poste
    environment:
      - TZ=Asia/Taipei
      - DISABLE_CLAMAV=TRUE
      - DISABLE_RSPAMD=TRUE
      - VIRTUAL_HOST=mail.${DOMAIN_NAME}
      - HTTPS=OFF
      - HTTP_PORT=80
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./data/poste:/data
      - ./conf/ssl:/etc/letsencrypt/live
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./conf/ssl:/etc/letsencrypt/live
    restart: always
